basic_app/urls.py
from django.urls import path
from basic_app import views

#template urls
app_name='basic_app'
urlpatterns = [
    path('register/',views.register, name="register"),
    path('user_login/',views.user_login,name="user_login"),
    path('user_logout/',views.user_logout,name="logout"),
    path('special/',views.special,name="special"),
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views


urlpatterns = [
    path('',views.index,name="index"),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
    #path('user_logout/',views.user_logout,name="logout"),
   # path('special/',views.special,name="special"),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #additional
    portfolio_site  = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basic_app/views.py
from django.shortcuts import render,redirect
from basic_app.forms import UserForm,UserProfileInfoForm

#from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse
from django.contrib.auth.models import User,auth
#from django.contrib.auth.decorators import login_required
#from django.urls import reverse




# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

def register(request):
    
    registered = False
    if request.method == "POST":
        
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'basic_app/registration.html',
                        {'user_form':user_form,
                        'profile_form':profile_form,
                        'registered':registered })

def user_login(request):

    if request.method =='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username , password=password)

        if user:
            if user.is_active:
                auth.login(request,user)
                return redirect("/")

            else:
                return HttpResponse("Account not active")

        else:
            print("Someone tried to login and failed")
            print("Username:{} and Password:{}".format(username,password))
            return HttpResponse("Invalid login details supplied")

    else:
        return render(request,'basic_app/login.html',{})

#@login_required
def special(request):
    return HttpResponse('You are logged in,nice!')

#@login_required
def user_logout(request):
    auth.logout(request)
    return redirect("/")
  

templates/basic_app/base.html
<!DOCTYPE html>
<html>
    <head>
      <meta charset = "utf-8">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
      <title></title>
    </head>
    <body> 
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div class="container">
                <div class="navbar-nav">
                    <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
                    <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>

                    {% if user.is_authenticated %}

                      <a class="nav-link" href="{% url 'logout' %}">Logout</a>

                    {% else %}

                      <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>

                    {% endif %}
                </div>
               
              </div>
            </nav>

            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
    </body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}

{% block content %}
    <div class="container">
        <div class ="jumbotron">
            <h1>django level five</h1>
        </div>
    </div>
{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block content %}
<div class = "jumbotron">
   <h1>please login</h1>
   <form action="{% url 'basic_app:user_login' %}" method = 'POST'>
       {% csrf_token %}
       <label for = "username">Username:</label>
       <input type = "text" name = "username" placeholder="Enter Username">
       <label for = "password">Password:</label>
       <input type = "password" name ="password">
       <input type = "Submit" name=" " value="Login">
   </form>
</div>
{% endblock %}

templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block content %}

   <div class="jumbotron">
       {% if registered %}
           <h1>Thank you for registering!</h1>
        {% else %}
           <h1>Register here!</h1>
           <h3>Fill out the form:</h3>
            <form enctype="multipart/form_data" method="post">
               {% csrf_token %}
               {{ user_form.as_p}}
               {{ profile_form.as_p}}
               <input type="submit" name="" value="Register">
            </form>
       {% endif %}
   </div>
{% endblock %}